name: Run Liner and tests

on: [ push ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: E2E Test
        run: npm run e2e:ci

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint
